//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSimplicity.MVC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppSimplicity.MVC.Localization.DefaultDateHandler, AppSimplicity.MVC")]
        public string DateHandlerProvider {
            get {
                return ((string)(this["DateHandlerProvider"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>~/Views/{1}/{0}.cshtml</string>
  <string>~/Views/{1}/Default/{0}.cshtml</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ViewLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ViewLocations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>~/Views/{1}/{0}_.cshtml</string>
  <string>~/Views/{1}/Default/{0}_.cshtml</string>
  <string>~/Views/Shared/{0}_.cshtml</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PartialViewLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PartialViewLocations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/assets/navigation/sitemap.{0}.xml")]
        public string SitemapLocation {
            get {
                return ((string)(this["SitemapLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppSimplicity.MVC.Navigation.DefaultMenuLoader, AppSimplicity.MVC")]
        public string NavigationProvider {
            get {
                return ((string)(this["NavigationProvider"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCultureForDateFormatting {
            get {
                return ((bool)(this["UseCultureForDateFormatting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${0:#,###,##0.00}")]
        public string GlobalCurrencyFormat {
            get {
                return ((string)(this["GlobalCurrencyFormat"]));
            }
        }
    }
}
